environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"
